name: GitHub Actions Demo
on:
  push:
    branches:    
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ è§¦å‘åŠ¨ä½œï¼š${{ github.event_name }}"
      - run: echo "ğŸ§ æ‰˜ç®¡æœåŠ¡å™¨ï¼š${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” å½“å‰åˆ†æ”¯ï¼š${{ github.ref }} "
      - run: echo "ğŸ  å½“å‰ä»“åº“ï¼š${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ è·å–æºç ï¼šThe ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ å·¥ä½œæµå‡†å¤‡ï¼šThe workflow is now ready to test your code on the runner."
      - name: Build and Deploy
        run: |
          yarn install
          yarn build
      - run: echo "âœ…ä¾èµ–å®‰è£…å¹¶ç¼–è¯‘å®Œæˆ"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # é»˜è®¤ç¯å¢ƒå˜é‡
          publish_dir: docs/.vuepress/dist # å‘å¸ƒæœ¬åœ°æ–‡ä»¶åœ°å€
      - run: echo "ğŸ This job's status is ${{ job.status }}."

# workflow æ–‡æ¡£æµé‡Œæˆ‘ä»¬å¯ä»¥ç”¨ ${{ secrets.GITHUB_TOKEN }} åšæƒé™è®¤è¯ï¼Œæ˜¯ä¸€ä¸ªé»˜è®¤å­˜åœ¨çš„å˜é‡ï¼Œå¹¶ä¸éœ€è¦æˆ‘ä»¬å»æ·»åŠ  ACCESS_TOKEN ï¼Œå½“ç„¶ä½ ä¹Ÿå¯ä»¥è‡ªå·±æ·»åŠ è‡ªå·±çš„ token åˆ°é¡¹ç›®çš„ secrets é‡Œå¹¶ä½¿ç”¨ã€‚
# FOLDER æ˜¯ build ä¹‹åç”Ÿæˆçš„ä»£ç ä½ç½®ï¼Œå¦‚æœä½ æ˜¯ vue ã€react ç­‰é¡¹ç›®å¯èƒ½åœ¨æ ¹ç›®å½• build æ–‡ä»¶å¤¹ä¸‹ï¼Œé‚£å°±å†™æˆ build ã€‚
